[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
holy_wars = "FHj8baQvc17Qny8TvndTtkjh2iqKgu9ucQgynwD6J1WG"

[programs.localnet]
holy_wars = "FHj8baQvc17Qny8TvndTtkjh2iqKgu9ucQgynwD6J1WG"
verifier_spike = "FTRE4a6SSMs1Y7NdLPKRnFAfGv5QhZKaW7aQPBzPT3m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json tests/holy-wars-core.ts --timeout 120000"
test-vote = "npx ts-mocha -p ./tsconfig.json tests/holy-wars-core.ts --timeout 180000"
